In [1]:
import sys
sys.path.append("../")

In [2]:
import json
import os
import pandas as pd

from src.database_utils.db_info import get_preprocessed_data
from src.database_utils.evaluate import get_snowflake_sql_result, compare_pandas_table

In [3]:
instane_id = "sf_bq012"

preprocessed_data = get_preprocessed_data(instane_id)
sql_query = preprocessed_data["query"]
database_id = preprocessed_data["db_id"]
is_save = True
save_dir = None
file_name = "result.csv"

In [4]:
status, df = get_snowflake_sql_result(sql_query, database_id, is_save=False, save_dir="./", file_name="result.csv")
df

  average_balance_trillion
0              26327002.23

In [5]:
compare_pandas_table(df, df)

condition_cols []
The status of our query is True.
The status of generated query is True.
The status of generated query without group by is True.
condition_cols []
The result of comparing our query and generated query is 0.
condition_cols []
The result of comparing our query and generated query without group by is 0.
condition_cols []
The result of comparing our query and generated query is 0.
condition_cols []
The result of comparing our query and generated query without group by is 0.
condition_cols []
condition_cols []
condition_cols []
The status of our query is True.
The status of generated query is True.
The status of generated query without group by is True.
condition_cols []
condition_cols []
condition_cols []
condition_cols []
condition_cols []
The status of our query is True.
The status of generated query is True.
The status of generated query without group by is True.
condition_cols []
condition_cols []
condition_cols []

1

In [7]:
dag_path = "/Users/stalaei/Desktop/Projects/Spider2/logs/decomposed_sqls/test/dag_sf_bq012.json"
dag = json.load(open(dag_path, 'r', encoding='utf-8'))
dag[0].keys()

dict_keys(['id', 'description', 'equivalent_natural_question', 'sql_query', 'dag_dependencies'])

In [8]:
from IPython.display import display

# Force output to display in notebook cell
from IPython.display import display, Markdown

for node in dag:
    # Use display() instead of print for notebook output
    display(Markdown(f"""
**Id:** {str(node.get('id', 'No ID found'))}

**Description:** {str(node.get('description', 'No description found'))}

**Results:**
"""))
    
    # Add error handling for missing sql_query
    if "sql_query" not in node:
        display(Markdown("Error: No SQL query found in node"))
        continue
        
    status, df = get_snowflake_sql_result(node["sql_query"], database_id, is_save=False)
    if status:
        display(df.head())
    else:
        display(Markdown(f"Error executing query: {df}"))
    display(Markdown("---"))

**Id:** A

**Description:** Filters the Ethereum TRACES table for successful transactions (status = 1) with to_address not null, excluding call types (delegatecall, callcode, staticcall). Each qualifying row represents Ether credited to the to_address.

**Results:**

                                      address                          value
0  0xea674fdde714fd979de3edf0f56aa9716b898ec8  5000000000000000000.000000000
1  0xb2930b35844a230f00e51431acae96fe543a0347  5000000000000000000.000000000
2  0x2a65aca4d5fc5b5c859090a6c34d164135398226  3000000000000000000.000000000
3  0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5  5000000000000000000.000000000
4  0xea674fdde714fd979de3edf0f56aa9716b898ec8  5000000000000000000.000000000

---

**Id:** B

**Description:** Similar filter on the TRACES table for successful transactions, but focusing on the from_address. Each qualifying row represents Ether debited from the from_address (i.e., how much Ether the sender transferred out).

**Results:**

                                      address value
0  0x6ca859d4f9a632ddf99d405b826409fd8a61539d  0E-9
1  0xe27d5876d71c2a3dbaf9a8394c031869b3ae1dd7  0E-9
2  0x094e5dca672bdca248e1a52bd9c15d7549907962  0E-9
3  0x4c3e3ec831e6f48a4d51f43bc54df64c26b116d7  0E-9
4  0x99f2b16a93705e464cbbdad7e515e0ec97770dbb  0E-9

---

**Id:** C

**Description:** Joins TRANSACTIONS with BLOCKS to identify each block's miner, and sums the gas fees (receipt_gas_used * gas_price) that go to that miner.

**Results:**

Error executing query: expected str, bytes or os.PathLike object, not NoneType

---

**Id:** D

**Description:** Calculates how much Ether each sender (from_address) paid in gas fees (receipt_gas_used * gas_price) over all transactions. This is a negative outflow for the sender.

**Results:**

                                      address              value
0  0x74a6c4823d81cbd6393e5957ccec128799a3f0c2 -22020096000000000
1  0x731e6cc591b055001ccb9758008f636819df6152  -1315840000000000
2  0xc1a1a63c331fc442bbbd04f32b923f8aa5f9f954   -527360000000000
3  0x3ba6c0229cdedfb99785d6193121c90a6e9085d1   -469504000000000
4  0x00bdb5699745f5b860228c8f939abf1b9ae374ed  -1892352000000000

---

**Id:** E

**Description:** Combines the results of the previous sub-components into one ledger-like table. Specifically, it gathers: Inflows for addresses receiving Ether (from the Traces data), Outflows for addresses sending Ether (also from the Traces), Gas fees earned by miners, and Gas fees paid by senders. All are unified with UNION ALL, so each address's credits and debits appear in a single list.

**Results:**

                                      address                          value
0  0xea674fdde714fd979de3edf0f56aa9716b898ec8  3000000000000000000.000000000
1  0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c  3000000000000000000.000000000
2  0xea674fdde714fd979de3edf0f56aa9716b898ec8  5000000000000000000.000000000
3  0x61c808d82a3ac53231750dadc13c777b59310bd9  5000000000000000000.000000000
4  0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5  5000000000000000000.000000000

---

**Id:** F

**Description:** Identifies the top 10 addresses (by net balance) from the ledger created in the previous sub-component.

**Results:**

,address,balance
0,0x7727e5113d1d161373623e5f49fd568b4f543a9e,38117709844226507899655.000000000
1,0x209c4784ab1e8183cf58ca33cb740efbf3fc18ef,35474695192161340660664.000000000
2,0xcff5a79f5d2dfc8b10569c6bb105194cb87a10be,28747477551000000000000.000000000
3,0x22b84d5ffea8b801c0422afe752377a64aa738c2,27030229490926374307329.000000000
4,0x93025150b13eb744d51d927549a30630912e8fe8,26963808902597776881025.000000000

---

**Id:** G

**Description:** Calculates the average of the top 10 balances in quadrillions (1e15), rounding to two decimals—this is the final result of the main question.

**Results:**

  average_balance_trillion
0              26327002.23

---

In [10]:
generated_dag_queries_path = "/Users/stalaei/Desktop/Projects/Spider2/logs/generated_queries/logs/decomposed_sqls/test/gemini-1.5-pro-002-20250129-120811/sf_bq012.json"
generated_dag_queries = json.load(open(generated_dag_queries_path, 'r', encoding='utf-8'))
generated_dag_queries[0].keys()

dict_keys(['id', 'description', 'equivalent_natural_question', 'sql_query', 'dag_dependencies', 'generated_queries', 'sql_meta_data_info'])

In [20]:
our_query = """
SELECT
    "to_address" AS "address",
    "value" AS "value"
FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE "to_address" IS NOT NULL
    AND "status" = 1
    AND ("call_type" NOT IN ('delegatecall', 'callcode', 'staticcall') OR "call_type" IS NULL)
"""

status, our_df = get_snowflake_sql_result(our_query, database_id, is_save=False)
print(f"The status of our query is {status}.")


generated_query = """
SELECT "to_address", SUM("value") AS total_ether_received
FROM "ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE "status" = 1 AND ("call_type" IS NULL OR "call_type" = 'call') AND "to_address" IS NOT NULL
GROUP BY "to_address";
"""

status, generated_df = get_snowflake_sql_result(generated_query, database_id, is_save=False)
print(f"The status of generated query is {status}.")

generated_query_without_group_by = """
SELECT "to_address", "value"
FROM "ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE "status" = 1 AND ("call_type" IS NULL OR "call_type" = 'call') AND "to_address" IS NOT NULL
"""

status, generated_df_without_group_by = get_snowflake_sql_result(generated_query_without_group_by, database_id, is_save=False)
print(f"The status of generated query without group by is {status}.")

In [21]:
compare_pandas_table(our_df, our_df)

1

In [22]:
compare_pandas_table(our_df, generated_df, ignore_order=True)

0

In [23]:
compare_pandas_table(our_df, generated_df_without_group_by, ignore_order=True)

1

In [9]:
print(f"The result of comparing our query and generated query is {compare_pandas_table(our_df, generated_df)}.")
print(f"The result of comparing our query and generated query without group by is {compare_pandas_table(our_df, generated_df_without_group_by)}.")

In [16]:
from IPython.display import display, Markdown

for node in generated_dag_queries:
    # Display node info
    display(Markdown(f"""
**Id:** {str(node.get('id', 'No ID found'))}

**Question:** {str(node.get('equivalent_natural_question', 'No question found'))}

**Description:** {str(node.get('description', 'No description found'))}

**Original Query Results:**
"""))
    
    # Execute and display original query results
    if "sql_query" not in node:
        display(Markdown("Error: No SQL query found in node"))
        continue

    display(Markdown(f"""
**Original Query:**
```sql
{node["sql_query"]}
```
"""))
        
    status, orig_df = get_snowflake_sql_result(node["sql_query"], database_id, is_save=False)
    if status:
        display(orig_df.head())
    else:
        display(Markdown(f"Error executing original query: {orig_df}"))
    
    # Loop through candidates
    display(Markdown("\n**Generated Query Results:**"))
    
    for i, candidate in enumerate(node['generated_queries']['candidates']):
        display(Markdown(f"\nCandidate {i+1}:"))
        generated_query = candidate.get('generated_query')
        
        if not generated_query:
            display(Markdown("No generated query found"))
            continue
            
        display(Markdown(f"""
**Generated Query:**
```sql
{generated_query}
```
"""))
        status, gen_df = get_snowflake_sql_result(generated_query, database_id, is_save=False)
        if status:
            display(gen_df.head())
            # Compare results
            if orig_df.equals(gen_df):
                display(Markdown("✅ Results match original query"))
            else:
                display(Markdown("❌ Results differ from original query"))
        else:
            display(Markdown(f"Error executing generated query: {gen_df}"))
    
    display(Markdown("---"))

**Id:** A

**Question:** Which addresses on Ethereum have received Ether in straightforward, successful transactions (not using special call types), and how much Ether did each receive in total?

**Description:** Filters the Ethereum TRACES table for successful transactions (status = 1) with to_address not null, excluding call types (delegatecall, callcode, staticcall). Each qualifying row represents Ether credited to the to_address.

**Original Query Results:**

**Original Query:**
```sql
SELECT
    "to_address" AS "address",
    "value" AS "value"
  FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRACES"
  WHERE "to_address" IS NOT NULL
    AND "status" = 1
    AND ("call_type" NOT IN ('delegatecall', 'callcode', 'staticcall') OR "call_type" IS NULL)
```

                                      address                          value
0  0xea674fdde714fd979de3edf0f56aa9716b898ec8  5000000000000000000.000000000
1  0xb2930b35844a230f00e51431acae96fe543a0347  5000000000000000000.000000000
2  0x2a65aca4d5fc5b5c859090a6c34d164135398226  3000000000000000000.000000000
3  0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5  5000000000000000000.000000000
4  0xea674fdde714fd979de3edf0f56aa9716b898ec8  5000000000000000000.000000000

**Generated Query Results:**

Candidate 1:

**Generated Query:**
```sql

SELECT "to_address", SUM("value") AS total_ether_received
FROM "ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE "status" = 1 AND ("call_type" IS NULL OR "call_type" = 'call') AND "to_address" IS NOT NULL
GROUP BY "to_address";

```

,to_address,TOTAL_ETHER_RECEIVED
0,0x1a060b0604883a99809eb3f798df71bef6c358f1,35468750000000000000.000000000
1,0x6bd264b7c9e0575d2cea562d9b7440dfc1612fcf,9000000000000000000.000000000
2,0x0064454b14cddc990ed6520ef94d3e28fe7c41b6,84866342110000000000.000000000
3,0x62f45ca24218cd10d7ecc2d9773766a88b90596d,1873670381772138250000.000000000
4,0x0243c652dd7ed97f8ffb53a652a4e273bdf9421f,1000164377166762763.000000000

❌ Results differ from original query

Candidate 2:

**Generated Query:**
```sql

SELECT "to_address", SUM("value") AS total_ether_received
FROM "ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE "status" = 1 AND ("call_type" IS NULL OR "call_type" = 'call') AND "to_address" IS NOT NULL
GROUP BY "to_address";

```

,to_address,TOTAL_ETHER_RECEIVED
0,0x1a060b0604883a99809eb3f798df71bef6c358f1,35468750000000000000.000000000
1,0x6bd264b7c9e0575d2cea562d9b7440dfc1612fcf,9000000000000000000.000000000
2,0x0064454b14cddc990ed6520ef94d3e28fe7c41b6,84866342110000000000.000000000
3,0x62f45ca24218cd10d7ecc2d9773766a88b90596d,1873670381772138250000.000000000
4,0x0243c652dd7ed97f8ffb53a652a4e273bdf9421f,1000164377166762763.000000000

❌ Results differ from original query

---

**Id:** B

**Question:** Which addresses on Ethereum have sent Ether in straightforward, successful transactions (ignoring special call types), and how much Ether did each send in total?

**Description:** Similar filter on the TRACES table for successful transactions, but focusing on the from_address. Each qualifying row represents Ether debited from the from_address (i.e., how much Ether the sender transferred out).

**Original Query Results:**

**Original Query:**
```sql
SELECT
    "from_address" AS "address",
    - "value" AS "value"
  FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRACES"
  WHERE "from_address" IS NOT NULL
    AND "status" = 1
    AND ("call_type" NOT IN ('delegatecall', 'callcode', 'staticcall') OR "call_type" IS NULL)
```

                                      address value
0  0x6ca859d4f9a632ddf99d405b826409fd8a61539d  0E-9
1  0xe27d5876d71c2a3dbaf9a8394c031869b3ae1dd7  0E-9
2  0x094e5dca672bdca248e1a52bd9c15d7549907962  0E-9
3  0x4c3e3ec831e6f48a4d51f43bc54df64c26b116d7  0E-9
4  0x99f2b16a93705e464cbbdad7e515e0ec97770dbb  0E-9

**Generated Query Results:**

Candidate 1:

**Generated Query:**
```sql

SELECT "from_address", SUM("value") AS total_ether_sent
FROM "ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE ("call_type" IS NULL OR "call_type" = 'call') AND "status" = 1
GROUP BY "from_address";

```

                                 from_address               TOTAL_ETHER_SENT
0  0x2e6ae3f47a75f5834726e475d77e5b3bc0d1d207                           0E-9
1  0x6040348a94f3756d5ce7e9b3500b33d1638452a7       75000000000000.000000000
2  0x10213d4f0efb78ad09bd5308db86ae633bbce544  2100000000000000000.000000000
3  0x7127943948bf06807374129e24af51f00bb45259    72739500000000000.000000000
4  0x506f8d17118c392055e6880a5afc817cf16d5cd1       55000000000000.000000000

❌ Results differ from original query

Candidate 2:

**Generated Query:**
```sql

SELECT "from_address", SUM("value") AS total_ether_sent
FROM "ETHEREUM_BLOCKCHAIN"."TRACES"
WHERE ("call_type" IS NULL OR "call_type" = 'call') AND "status" = 1
GROUP BY "from_address";

```

                                 from_address               TOTAL_ETHER_SENT
0  0x2e6ae3f47a75f5834726e475d77e5b3bc0d1d207                           0E-9
1  0x6040348a94f3756d5ce7e9b3500b33d1638452a7       75000000000000.000000000
2  0x10213d4f0efb78ad09bd5308db86ae633bbce544  2100000000000000000.000000000
3  0x7127943948bf06807374129e24af51f00bb45259    72739500000000000.000000000
4  0x506f8d17118c392055e6880a5afc817cf16d5cd1       55000000000000.000000000

❌ Results differ from original query

---

**Id:** C

**Question:** Looking at all Ethereum blocks, how much total gas fee did each miner collect from all the transactions in their blocks?

**Description:** Joins TRANSACTIONS with BLOCKS to identify each block's miner, and sums the gas fees (receipt_gas_used * gas_price) that go to that miner.

**Original Query Results:**

**Original Query:**
```sql
SELECT
    "miner" AS "address",
    SUM(CAST("receipt_gas_used" AS NUMBER) * CAST("gas_price" AS NUMBER)) AS "value"
  FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRANSACTIONS" AS "transactions"
  JOIN "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."BLOCKS" AS "blocks"
    ON "blocks"."number" = "transactions"."block_number"
  GROUP BY "blocks"."miner"
```

Error executing original query: expected str, bytes or os.PathLike object, not NoneType

**Generated Query Results:**

Candidate 1:

**Generated Query:**
```sql

SELECT "b"."miner", SUM("t"."receipt_gas_used" * "t"."gas_price") AS total_gas_fees
FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."BLOCKS" AS "b"
JOIN "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRANSACTIONS" AS "t" ON "b"."number" = "t"."block_number"
GROUP BY "b"."miner";

```

Error executing generated query: expected str, bytes or os.PathLike object, not NoneType

Candidate 2:

**Generated Query:**
```sql

SELECT "b"."miner", SUM("t"."receipt_gas_used" * "t"."gas_price") AS total_gas_fees
FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."BLOCKS" AS "b"
JOIN "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRANSACTIONS" AS "t" ON "b"."number" = "t"."block_number"
GROUP BY "b"."miner";

```

Error executing generated query: expected str, bytes or os.PathLike object, not NoneType

---

**Id:** D

**Question:** For every Ethereum transaction, how much gas fee did the sender pay, and what is the total gas fee spending by each sending address over time?

**Description:** Calculates how much Ether each sender (from_address) paid in gas fees (receipt_gas_used * gas_price) over all transactions. This is a negative outflow for the sender.

**Original Query Results:**

**Original Query:**
```sql
SELECT
    "from_address" AS "address",
    -(CAST("receipt_gas_used" AS NUMBER) * CAST("gas_price" AS NUMBER)) AS "value"
  FROM "ETHEREUM_BLOCKCHAIN"."ETHEREUM_BLOCKCHAIN"."TRANSACTIONS"
```

                                      address              value
0  0x74a6c4823d81cbd6393e5957ccec128799a3f0c2 -22020096000000000
1  0x731e6cc591b055001ccb9758008f636819df6152  -1315840000000000
2  0xc1a1a63c331fc442bbbd04f32b923f8aa5f9f954   -527360000000000
3  0x3ba6c0229cdedfb99785d6193121c90a6e9085d1   -469504000000000
4  0x00bdb5699745f5b860228c8f939abf1b9ae374ed  -1892352000000000

**Generated Query Results:**

Candidate 1:

**Generated Query:**
```sql

SELECT "from_address", "receipt_gas_used" * "gas_price" AS gas_fee_per_tx, SUM("receipt_gas_used" * "gas_price") OVER (PARTITION BY "from_address") AS total_gas_fee_spending
FROM "ETHEREUM_BLOCKCHAIN"."TRANSACTIONS";

```

,from_address,GAS_FEE_PER_TX,TOTAL_GAS_FEE_SPENDING
0,0x9ddc772bbfd702d2a1e246cd6dd26a312f15eef7,786030000000000,30380200000000000
1,0x9ddc772bbfd702d2a1e246cd6dd26a312f15eef7,786030000000000,30380200000000000
2,0x4fbda70fe3047a2764aeb621cb7857ca6cc385c5,471618000000000,471618000000000
3,0x2b5634c42055806a59e9107ed44d43c426e58258,789870000000000,376448475635698409
4,0x0681d8db095565fe8a346fa0277bffde9c0edbbf,2106320000000000,1858995040000000000

❌ Results differ from original query

Candidate 2:

**Generated Query:**
```sql

SELECT "from_address", "receipt_gas_used" * "gas_price" AS gas_fee_per_transaction, SUM("receipt_gas_used" * "gas_price") OVER (PARTITION BY "from_address") AS total_gas_fee_spending
FROM "ETHEREUM_BLOCKCHAIN"."TRANSACTIONS";

```

,from_address,GAS_FEE_PER_TRANSACTION,TOTAL_GAS_FEE_SPENDING
0,0x9ddc772bbfd702d2a1e246cd6dd26a312f15eef7,786030000000000,30380200000000000
1,0x9ddc772bbfd702d2a1e246cd6dd26a312f15eef7,786030000000000,30380200000000000
2,0x4fbda70fe3047a2764aeb621cb7857ca6cc385c5,471618000000000,471618000000000
3,0x2b5634c42055806a59e9107ed44d43c426e58258,789870000000000,376448475635698409
4,0x0681d8db095565fe8a346fa0277bffde9c0edbbf,2106320000000000,1858995040000000000

❌ Results differ from original query

---